### ISSUE TITLE
event-statusReason problem

### ISSUE THREAD

**Issue by mvdzel** [mvdzel/vha-ampl-fhir-ig#19]
```
Exception generating resource /home/node/vha-ampl-fhir-ig/input/resources/StructureDefinition-event-statusReason::StructureDefinition/event-statusReason: Index: 0, Size: 0 (02:14.0363)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.hl7.fhir.igtools.renderers.StructureDefinitionRenderer.pseudoJson(StructureDefinitionRenderer.java:1488)
	at org.hl7.fhir.igtools.publisher.Publisher.generateOutputsStructureDefinition(Publisher.java:7644)
	at org.hl7.fhir.igtools.publisher.Publisher.generateResourceHtml(Publisher.java:6667)
	at org.hl7.fhir.igtools.publisher.Publisher.generateHtmlOutputs(Publisher.java:6611)
	at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:4873)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:884)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:728)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8373)
```

**Comment by mvdzel** [comment]
The id and url are different. Is that a problem?
 "id": "event-statusReason"
 "url": "http://va.gov/fhir/StructureDefinition/event-processState"

**Comment by mvdzel** [comment]
Workaround by comment out in myig.xml.

**Comment by mvdzel** [comment]
Caused by a typo in the datatype of this extension in fhirProperties.
There is an extra 'l' in 'codeablelConcept'
